# Generated by Django 5.1.4 on 2025-01-09 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currently_date', models.DateTimeField(verbose_name='Вход на данный момент')),
                ('currently_date_exit', models.DateTimeField(verbose_name='Выход на данный момент')),
                ('enter_date', models.DateTimeField(verbose_name='Дата входа')),
                ('exit_date', models.DateTimeField(verbose_name='Дата выхода')),
                ('default_work_star_time', models.DateTimeField(blank=True, null=True, verbose_name='Время работы по умолчанию')),
                ('default_work_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец рабочего дня по умолчанию')),
                ('total_minutes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Общее время в минутах')),
                ('total_minutes_late', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Общее время опоздание в минутах')),
                ('late', models.BooleanField(default=False, verbose_name='Опоздание')),
                ('visit_default_closed_by_system', models.BooleanField(default=False, verbose_name='Закрыто по умолчанию')),
                ('manual_created', models.BooleanField(default=False, verbose_name='Создано вручную')),
                ('manual_updated', models.BooleanField(default=False, verbose_name='Обновлено вручную')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_visits', to='department.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-currently_date'],
            },
        ),
    ]
