# Generated by Django 5.1.4 on 2025-01-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время Создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('on_subscription', 'On_subscription')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончания подписки'),
        ),
    ]
