# Generated by Django 5.1.4 on 2025-01-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Сумма начисления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Кометарии')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата получения бонуса')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to='company.company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.staff')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Сумма списания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдвчи')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='company.company')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.staff')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
            },
        ),
    ]
