# Generated by Django 5.1.4 on 2025-01-09 05:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=100)),
                ('start_work_time', models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня')),
                ('allowed_lateness', models.IntegerField(verbose_name='Фора опоздания в минутах')),
                ('end_work_time', models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня')),
                ('lateness_penalty', models.BooleanField(verbose_name='Штраф за опоздания')),
                ('lateness_penalty_per_min', models.IntegerField(verbose_name='Штраф за опоздания в мин')),
                ('sum_penalty', models.IntegerField(default=0, verbose_name='Сумма штрафа')),
                ('close_attendance', models.BooleanField(default=True, verbose_name='Закрывать посешения по умолчанию')),
                ('lunch_time', models.TimeField(blank=True, null=True, verbose_name='Время обеда')),
                ('allowed_lunch_time', models.IntegerField(verbose_name='Фора за посешение обеда')),
                ('end_lunch', models.TimeField(blank=True, null=True, verbose_name='Конец Обеда')),
                ('salary_for_lunch', models.BooleanField(verbose_name='Начисления зп за обед')),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=6)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя(на англ)')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия(на англ)')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус')),
                ('date_of_birth', models.DateField(verbose_name='Дата Рождения')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('salary_stratage', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2, verbose_name='Стратегия зп(месяц, час)')),
                ('balance', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('is_flexible_schedule', models.BooleanField(blank=True, default=False, null=True, verbose_name='Персональный график сотрудника')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='начало работы')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='конец работы')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='department.department')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
