# Generated by Django 5.1.4 on 2025-01-17 04:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name_of_department',
            field=models.CharField(max_length=100, verbose_name='Название Отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='weekend_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=6, verbose_name='Выходной день'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='department.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_flexible_schedule',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Кастомный график сотрудника'),
        ),
    ]
