# Generated by Django 5.1.4 on 2025-01-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_name_of_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='weekend_days',
            field=models.CharField(blank=True, choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресения')], null=True, verbose_name='Выходной день'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary_stratage',
            field=models.CharField(choices=[('Month', 'Месяц'), ('Hour', 'Час')], verbose_name='Стратегия зп(месяц, час)'),
        ),
    ]
