# Generated by Django 5.1.4 on 2025-01-09 05:29

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours_overworked', models.IntegerField(default=12)),
                ('time_send_sms', models.IntegerField(default=2)),
                ('allow_exit', models.IntegerField(default=2)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('repeat_type', models.CharField(choices=[('ONCE', 'ONCE'), ('DALLY', 'DALLY'), ('WEEKDAY', 'WEEKDAY')], default='ONCE', max_length=100)),
                ('repeat_day', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='The number of days that the event repeats.', null=True, size=6)),
                ('start_date_time', models.DateTimeField(default=datetime.date.today)),
                ('end_date_time', models.DateTimeField(default=datetime.date.today)),
                ('bonus_salary', models.BooleanField(default=False)),
                ('lateness_penalty', models.BooleanField(default=False)),
                ('penalty_per_min', models.IntegerField(default=0)),
                ('total_penalty', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='company.company')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('text_message', models.CharField(max_length=200)),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('chosen_staff', models.ManyToManyField(related_name='chosen_staff', to='department.staff')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='company.company')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('chosen_staff', models.ManyToManyField(related_name='staffs_to_vacation', to='department.staff')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='company.company')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуски',
            },
        ),
    ]
