# Generated by Django 5.1.4 on 2025-01-27 09:33

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bonus_salary',
            field=models.BooleanField(default=False, verbose_name='Бонус за посещения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Время окончания события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, verbose_name='Название События'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lateness_penalty',
            field=models.BooleanField(default=False, verbose_name='Штраф за опоздания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='penalty_per_min',
            field=models.IntegerField(default=0, verbose_name='Штраф в минуту'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='The number of days that the event repeats.', null=True, size=6, verbose_name='Дни потвторения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_type',
            field=models.CharField(blank=True, choices=[('ONCE', 'Один раз'), ('DALLY', 'Каждый раз'), ('WEEKDAY', 'Каждую неделю')], max_length=100, null=True, verbose_name='Тип повторения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Время начало события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_penalty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Общий штраф'),
        ),
    ]
